### ISSUE TITLE
Support for google.protobuf.Timestamp as string

### ISSUE THREAD

**Issue by netanel-utila** [bufbuild/protobuf-es#1015]
Currently it returns:

```ts
{
  $typeName: "google.protobuf.Timestamp",
  seconds: 1727445165n,
  nanos: 865585000,
}
```

Migrating from ts-proto that supports useDate string:

```
version: v1
plugins:
  - name: ts_proto
    out: ../genproto/ts_web
    opt:
      - useDate=string
```

How can we do this using this library?
