### ISSUE TITLE
import xxx : file does not exist

### ISSUE THREAD

**Issue by cruvie** [bufbuild/protobuf-es#1042]
dir tree
![longshot20241230125418](https://github.com/user-attachments/assets/6f7a6b1b-80e0-4808-b57d-a4620529af93)

buf.gen.yaml
```yaml
version: v2
inputs:
  - directory: .
plugins:
  - local: protoc-gen-es
    opt: target=ts
    include_imports: true
    out: ./lib_ts
```
kk_rbac_api_permission.proto
```proto
syntax = "proto3";
package demo;
option go_package = "kk_go_kit/demo/base";
import "demo/kk_rbac_pb_permission.proto";

message KKRBACPermissionList {
  message Input {
  }

  message Output {
    PBListPermission List = 1;
  }
}

```

kk_rbac_pb_permission.proto
```proto
syntax = "proto3";
package demo;
import "google/protobuf/timestamp.proto";

option go_package = "kk_go_kit/demo/base";

message PBPermission {
  uint64 Id = 1;
  google.protobuf.Timestamp CreatedAt = 2;
  google.protobuf.Timestamp UpdatedAt = 3;
  int32 Status = 4;
  string Remark = 5;
  string ApiTag = 6;
  string ApiId = 7;
  string ApiName = 8;
}

message PBListPermission{
  repeated PBPermission List = 1;
}
```
run cmd
```sh
cruvie@CruvieMacAir-4 demo % npx buf generate
kk_rbac_api_permission.proto:4:8:import "demo/kk_rbac_pb_permission.proto": file does not exist
```
