### ISSUE TITLE
Import errors when using google/api/annotations.proto

### ISSUE THREAD

**Issue by paskozdilar** [bufbuild/protobuf-es#1055]
Here's a list of files and their contents required for minimal reproducible example:

buf.gen.yaml
```yaml
version: v2
managed:
  enabled: true
plugins:
  - remote: buf.build/bufbuild/es:v2.2.3
    out: gen
    opt:
      - target=ts
```

buf.yaml
```yaml
version: v2
modules:
  - path: proto
deps:
  - buf.build/googleapis/googleapis
```

proto/sample.proto
```protobuf
syntax = "proto3";

package sample;

import "google/api/annotations.proto";

service SampleService {
  rpc UnaryCall (SampleMessage) returns (SampleMessage) {
    option (google.api.http) = {
      post: "/unary";
      body: "*";
    };
  }
}

message SampleMessage {}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2016",                                  
    "module": "commonjs",                                
    "esModuleInterop": true,                             
    "forceConsistentCasingInFileNames": true,            
    "strict": true,                                      
    "skipLibCheck": true                                 
  }
}
```

package.json
```json
{
  "dependencies": {
    "@bufbuild/protobuf": "^2.2.3"
  },
  "devDependencies": {
    "@bufbuild/buf": "^1.49.0",
    "typescript": "^5.7.3"
  }
}
```

index.ts
```typescript
import * as sample from './gen/sample_pb';

console.log(sample.SampleMessageSchema);
```

Commands to run:
```
npm install
npx buf dep update
npx buf generate
npx tsc --build
```

Output:

```
npx tsc --build
gen/sample_pb.ts:10:45 - error TS2307: Cannot find module './google/api/annotations_pb' or its corresponding type declarations.

10 import { file_google_api_annotations } from "./google/api/annotations_pb";
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

For convenience, I've created a repository containing the reproducible example at [https://github.com/paskozdilar/protobuf-es-bug](https://github.com/paskozdilar/protobuf-es-bug).
