### ISSUE TITLE
Feature Request: Omit/Pick/Filter out services

### ISSUE THREAD

**Issue by bitttttten** [bufbuild/protobuf-es#1150]
```yml
version: v2
clean: true
plugins:
  - remote: buf.build/bufbuild/es:v2.0.0
    out: ./src/gen/service
    opt: target=ts
inputs:
  - git_repo: ssh://git@github.com/our/repo.git
    branch: main
    depth: 1
```

With the following config, we generate codegen for every service within our repo.git. However, we have quite a large collection of schemas and we'd like to only include certain ones like

```yml
plugins:
  - remote: buf.build/bufbuild/es:v2.0.0
    out: ./src/gen/service
    opt:
      - target=ts
      - include=service1,service2,service3
```
