### ISSUE TITLE
How do I specify a .proto files path?

### ISSUE THREAD

**Issue by shinebayar-g** [bufbuild/protobuf-es#339]
Hi, this may sound trivial, but I didn't find any documentation on how to specify a path to `.proto` files. My `.proto` files live in upper directory than my react project directory and I want to generate a client code for the `connect-web`. Could someone provide an example?

https://connect.build/docs/web/generating-code#local-generation uses this config 
```yaml
# buf.gen.yaml defines a local generation template.
# For details, see https://docs.buf.build/configuration/v1/buf-gen-yaml
version: v1
plugins:
  - name: es
    out: gen
    # With target=ts, we generate TypeScript files.
    # Use target=js+dts to generate JavaScript and TypeScript declaration files
    # like remote generation does.
    opt: target=ts
  - name: connect-web
    out: gen
    # With target=ts, we generate TypeScript files.
    opt: target=ts
```

with this script for `package.json`

```json
"scripts": {
    ...
    "buf:generate": "buf generate buf.build/bufbuild/eliza"
},
```
