### ISSUE TITLE
Document supported options

### ISSUE THREAD

**Issue by shinebayar-g** [bufbuild/protobuf-es#340]
What are the supported options for `opt` and their defaults?
```yaml
version: v1
plugins:
  - name: es
    out: proto/gen
    opt: target=ts
  - name: connect-web
    out: proto/gen
    opt: target=ts

```
