### ISSUE TITLE
toJson() does not output false values

### ISSUE THREAD

**Issue by pelzerim** [bufbuild/protobuf-es#388]
When a Message has a `bool` field that is set to `false`, the `toJson` does not output it.

This can be easily reproduced using the example from the [Quickstart in the README](https://github.com/bufbuild/protobuf-es#quickstart).

We however use javascript with typescript definitions:

```
version: v1
plugins:
   - name: es
     path: ./node_modules/.bin/protoc-gen-es
     opt: target=js+dts
     out: src/gen
```

This code outputs an empty object:

```
import { User } from './src/gen/example_pb.js'

const user = new User()
user.active = false

console.log(user.toJson({}))
```

Using `console.log(user.toJson({ emitDefaultValues: true }))`  does output the  `false` value though (which is the workaround we use now).

Is this desired behavior or a bug?
