### ISSUE TITLE
Generated typescript is importing a non existent file

### ISSUE THREAD

**Issue by juanpmarin** [bufbuild/protobuf-es#457]
Hi! I'm using buf to generate typescript code for my connect service.

`import "google/type/money.proto";` I'm using that import in my proto file, and the generated typescript  file is trying to import this file: `import { Money } from "../../../../google/type/money_pb.js";` which does not exist 

```
version: v1
plugins:
  - plugin: buf.build/protocolbuffers/go
    out: gen/go
    opt: paths=source_relative
  - plugin: buf.build/bufbuild/connect-go
    out: gen/go
    opt: paths=source_relative
  - plugin: buf.build/bufbuild/validate-go
    out: gen/go
    opt: paths=source_relative
  - plugin: buf.build/bufbuild/es
    out: gen/ts
    opt: target=ts
  - plugin: buf.build/bufbuild/connect-es
    out: gen/ts
    opt: target=ts
```
That's my buf gen config
