### ISSUE TITLE
Ability to generate source relative files (`paths=source_relative`)

### ISSUE THREAD

**Issue by leandro-branco** [bufbuild/protobuf-es#537]
It would be nice and useful to be able to generate files in a relative path (`paths=source_relative`) to the source `.proto` definitions like `go`, `go-grpc` and `connect-go` do:

```yaml
  - plugin: buf.build/bufbuild/connect-go:v1.10.0
    out: gen
    opt:
      - paths=source_relative
```
