### ISSUE TITLE
protoc-gen-es: Cannot read properties of undefined (reading 'BIGINT')

### ISSUE THREAD

**Issue by Mitch528** [bufbuild/protobuf-es#613]
After updating `@bufbuild/protoc-gen-es` from 1.3.1 to 1.4.2, I have started receving this error:

```
protoc-gen-es: Cannot read properties of undefined (reading 'BIGINT')
Failure: plugin es: exit status 1; exit status 1
```

buf.gen.yaml

```
version: v1
plugins:
  - plugin: es
    opt: target=ts
    out: src/gen
  - plugin: connect-es
    opt: target=ts
    out: src/gen
  - plugin: connect-query
    opt: target=ts
    out: src/gen
```

```
node --version
v21.1.0
```
