### ISSUE TITLE
The import is not working

### ISSUE THREAD

**Issue by jack-theripper** [bufbuild/protobuf-es#838]
Generates incorrect import code when

```
version: v1
plugins:
  - plugin: es
    opt: target=ts
    out: src/protobuf
```

Error: Cannot find module './packet_pb.js'

```ts
// packet9999_pb.ts:

import type { GenDescFile, GenDescMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Packet } from "./packet_pb.js";
import { fileDesc_packet } from "./packet_pb.js";
import type { Message } from "@bufbuild/protobuf";
```

```
import "packet.proto";

message Packet9999 {
	required int32 packet_id = 1;
	required MSG1 val = 2;
// ...
}

**Comment by srikrsna-buf** [comment]
It could be because of the `.js` extension. We generate `.js` as described in the ECMAScript spec. But bundlers haven't yet implemented it. You can use the `import_extension` option to remove the extension:
```yaml
version: v1
plugins:
  - plugin: es
    opt: target=ts,import_extension=none
    out: src/protobuf
```

If the import is coming from a buf module dependency, then you may need to run use the `--include-imports` flag
