### ISSUE TITLE
Unable to import @bufbuild/protobuf/codegenv1 in generated files.

### ISSUE THREAD

**Issue by HemantNegi** [bufbuild/protobuf-es#953]
Hi Team, 
Thanks for excellent work here.

Im generating the .ts files using buf, here is my configuration
``` yaml
  - remote: buf.build/bufbuild/es:v2.0.0
    out: typescript
    opt: target=ts,import_extension=none,json_types=true
    include_imports: true
```

I imported the generated files in my expo based project. But when I run the project it throws below error. 

```bash
Metro error: Unable to resolve module @bufbuild/protobuf/codegenv1 from /Users/hemant/projects/app/components/stubs/data-service/v1/data_pb.ts: @bufbuild/protobuf/codegenv1 could not be found within the project or in these directories:
  node_modules
  12 |
  13 | import type { GenEnum, GenExtension, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
> 14 | import { enumDesc, extDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
     |                                                                        ^
```

I verified the @bufbuild/protobuf is available in node_modules also did the cache cleanup. Even wrote a custom resolver for metro. But the error is still there.

Im not sure where to report this and whether this is an issue in the export config of bufbuild/protobuf.

Any help will be appreciated.
