### ISSUE TITLE
Dependencies in `buf.yml` not generated

### ISSUE THREAD

**Issue by leandro-branco** [bufbuild/protobuf-es#967]
Not sure if this is working as intended, but it seems the `buf generate` command is not taking into consideration the dependencies listed in `buf.yml` file. We're using v2.0.0, btw.

As a simple example, given:

```proto
// playground.proto
syntax = "proto3";

package api.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

message Ping {
  string message = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string = {
      min_len: 1;
      max_len: 20;
    }
  ];
}

message Pong {
  string message = 1 [
    (buf.validate.field).required = true
  ];
}

service PlaygroundService {
  rpc PingCmd(Ping) returns (Pong) {
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      tags: "Playground"
    };
  }
}
```

```yml
# buf.yml
version: v1
name: buf.build/acme/proj
deps:
  - buf.build/googleapis/googleapis
  - buf.build/bufbuild/protovalidate
  - buf.build/grpc-ecosystem/grpc-gateway
lint:
  use:
    - DEFAULT
    - COMMENTS
  except:
    - RPC_REQUEST_STANDARD_NAME
    - RPC_RESPONSE_STANDARD_NAME
    - RPC_REQUEST_RESPONSE_UNIQUE
    - PACKAGE_VERSION_SUFFIX
```

```yml
# buf.gen.yml
version: v1
plugins:
  - plugin: buf.build/bufbuild/es:v2.0.0
    out: .
    opt:
      - target=ts
      - import_extension=none
```

If we generate code for `playground.proto`, using the the `buf.yml` and `buf.gen.yml`, the generated code tries to import these annotations from a relative folder (snippet code below). However, these files don't exist. To do so, we're currently manually running `buf generate buf.build/buf.build/googleapis/googleapis` and the others:

```typescript
// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file src/api/v1/playground_service.proto (package api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file src/api/v1/playground_service.proto.
 */
export const file_src_api_v1_playground_service: GenFile = /*@__PURE__*/
  fileDesc("CiNzcmMvYXBpL3YxL3BsYXlncm91bmRfc2VydmljZS5wcm90bxIGYXBpLnYxIiUKBFBpbmcSHQoHbWVzc2FnZRgBIAEoCUIMukgJyAEBcgQQARgUIh8KBFBvbmcSFwoHbWVzc2FnZRgBIAEoCUIGukgDyAEBMksKEVBsYXlncm91bmRTZXJ2aWNlEjYKB1BpbmdDbWQSDC5hcGkudjEuUGluZxoMLmFwaS52MS5Qb25nIg+SQQwKClBsYXlncm91bmRiBnByb3RvMw", [file_buf_validate_validate, file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * A ping message
 *
 * @generated from message api.v1.Ping
 */
export type Ping = Message<"api.v1.Ping"> & {
  /**
   * The ping message
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message api.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_src_api_v1_playground_service, 0);

/**
 * A pong message
 *
 * @generated from message api.v1.Pong
 */
export type Pong = Message<"api.v1.Pong"> & {
  /**
   * The pong echoed message
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message api.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_src_api_v1_playground_service, 1);

/**
 * The playground service definition.
 *
 * @generated from service api.v1.PlaygroundService
 */
export const PlaygroundService: GenService<{
  /**
   * Simple ping pong
   *
   * @generated from rpc api.v1.PlaygroundService.PingCmd
   */
  pingCmd: {
    methodKind: "unary";
    input: typeof PingSchema;
    output: typeof PongSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_src_api_v1_playground_service, 0);
```
